#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FTTH Labeler — Release Build Script
====================================
Run this script to create a protected release ZIP.

Usage:
    python build_release.py --expiry 2026-12-31
    python build_release.py --expiry 2026-06-30 --name ftth_for_company_a
    python build_release.py --permanent --name ftth_permanent

Output:
    A ZIP file with compiled .pyc files only (no readable source code).
    The expiration date is embedded as an obfuscated constant.
"""

import argparse
import base64
import compileall
import os
import py_compile
import shutil
import struct
import sys
import tempfile
import zipfile
from datetime import datetime


def _obfuscate_date(date_str):
    """Obfuscate date string to hide it from casual reading."""
    # Simple XOR obfuscation with fixed key
    key = b"FTTH2024"
    data = date_str.encode('utf-8')
    obf = bytes(data[i] ^ key[i % len(key)] for i in range(len(data)))
    return base64.b64encode(obf).decode('ascii')


def _generate_license_module(obfuscated_date):
    """Generate the license module with embedded obfuscated date."""
    return f'''# -*- coding: utf-8 -*-
"""License module — auto-generated by build_release.py. DO NOT EDIT."""
import base64, hashlib, struct
from datetime import datetime, timedelta
from qgis.PyQt.QtCore import QSettings

# Obfuscated expiration date (format: YYYY-MM-DD)
_O = "{obfuscated_date}"
_D = lambda: base64.b64decode(_O).decode('utf-8')
_C = lambda s: bytes(a ^ b for a, b in zip(s, b"FTTH2024" * (len(s)//8 + 1)[:len(s)]))

def _get_expiry():
    try:
        raw = base64.b64decode(_O)
        dec = bytes(raw[i] ^ (b"FTTH2024"[i % 8]) for i in range(len(raw)))
        return dec.decode('utf-8')
    except Exception:
        return ""

# Settings keys (obfuscated)
_F = "ftth_labeler/_init_ts"
_L = "ftth_labeler/_last_ts"

CONTACT_NAME = "Mustafa M M Ellaham"
CONTACT_EMAIL = "Mustafaellaham@gmail.com"
WARNING_DAYS = 30


def _hash_date(date_str):
    return hashlib.md5(f"{{date_str}}::FTTH".encode()).hexdigest()[:12]


def _store_date(key, date_obj):
    date_str = date_obj.strftime("%Y%m%d")
    QSettings().setValue(key, f"{{date_str}}:{{_hash_date(date_str)}}")


def _read_date(key):
    try:
        raw = QSettings().value(key, "")
        if not raw or ":" not in raw:
            return None
        date_str, stored_hash = raw.split(":", 1)
        if _hash_date(date_str) != stored_hash:
            return "TAMPERED"
        return datetime.strptime(date_str, "%Y%m%d")
    except Exception:
        return None


def check_license():
    exp_str = _get_expiry()
    if not exp_str or not exp_str.strip():
        return True, "No expiration configured", None
    try:
        expiry = datetime.strptime(exp_str.strip(), "%Y-%m-%d")
    except ValueError:
        return False, "Invalid expiration configuration", None
    today = datetime.now()
    first_use = _read_date(_F)
    last_use = _read_date(_L)
    if first_use == "TAMPERED" or last_use == "TAMPERED":
        return False, (
            f"License validation failed: settings appear modified.\\n\\n"
            f"Contact {{CONTACT_NAME}} at {{CONTACT_EMAIL}} for support."
        ), None
    if first_use and today.date() < first_use.date():
        return False, (
            f"License validation failed: system clock rolled back.\\n"
            f"First use recorded on {{first_use.strftime('%Y-%m-%d')}}.\\n\\n"
            f"Contact {{CONTACT_NAME}} at {{CONTACT_EMAIL}}."
        ), None
    if last_use and today.date() < last_use.date():
        return False, (
            f"License validation failed: system clock rolled back.\\n"
            f"Last use recorded on {{last_use.strftime('%Y-%m-%d')}}.\\n\\n"
            f"Contact {{CONTACT_NAME}} at {{CONTACT_EMAIL}}."
        ), None
    if not first_use:
        _store_date(_F, today)
    _store_date(_L, today)
    if today.date() > expiry.date():
        return False, (
            f"Plugin license expired on {{exp_str}}.\\n\\n"
            f"Contact {{CONTACT_NAME}} at {{CONTACT_EMAIL}} to renew."
        ), 0
    days_left = (expiry.date() - today.date()).days
    return True, "License valid", days_left


def clear_license_data():
    s = QSettings()
    s.remove(_F)
    s.remove(_L)
'''


def build_release(expiry_date, output_name, plugin_dir):
    """Build a protected release ZIP."""
    print("=" * 60)
    print("FTTH Labeler — Release Build")
    print("=" * 60)
    print(f"Expiry date: {expiry_date or 'PERMANENT'}")
    print(f"Output:      {output_name}.zip")
    print("")

    # Validate date
    if expiry_date:
        try:
            datetime.strptime(expiry_date, "%Y-%m-%d")
        except ValueError:
            print("ERROR: Date must be YYYY-MM-DD format")
            return False

    # Create temp build directory
    build_dir = tempfile.mkdtemp(prefix="ftth_build_")
    print(f"Build dir: {build_dir}")

    try:
        # Copy plugin to build dir
        shutil.copytree(plugin_dir, os.path.join(build_dir, "ftth_labeler_v2"))
        build_plugin_dir = os.path.join(build_dir, "ftth_labeler_v2")

        # Remove old .pyc and __pycache__
        for root, dirs, files in os.walk(build_plugin_dir):
            if "__pycache__" in dirs:
                shutil.rmtree(os.path.join(root, "__pycache__"))
                dirs.remove("__pycache__")
            for f in files:
                if f.endswith(".pyc"):
                    os.remove(os.path.join(root, f))

        # Replace license_checker.py with generated obfuscated version
        obf_date = _obfuscate_date(expiry_date) if expiry_date else ""
        license_content = _generate_license_module(obf_date)
        license_path = os.path.join(build_plugin_dir, "license_checker.py")
        with open(license_path, 'w', encoding='utf-8') as f:
            f.write(license_content)
        print("  [OK] License module generated (obfuscated)")

        # Remove config.py (date is now embedded in license_checker)
        config_path = os.path.join(build_plugin_dir, "config.py")
        if os.path.exists(config_path):
            os.remove(config_path)
            print("  [OK] config.py removed (date embedded)")

        # Remove build_release.py from package
        build_script = os.path.join(build_plugin_dir, "build_release.py")
        if os.path.exists(build_script):
            os.remove(build_script)
            print("  [OK] build_release.py removed")

        # Compile all .py to .pyc
        print("  Compiling Python files...")
        for fname in os.listdir(build_plugin_dir):
            if fname.endswith(".py"):
                py_path = os.path.join(build_plugin_dir, fname)
                try:
                    py_compile.compile(py_path, doraise=True)
                except py_compile.PyCompileError as e:
                    print(f"  [ERROR] Compile failed: {fname}: {e}")
                    return False

        # Remove .py source files, keep only .pyc
        removed = 0
        for fname in os.listdir(build_plugin_dir):
            if fname.endswith(".py"):
                os.remove(os.path.join(build_plugin_dir, fname))
                removed += 1
        print(f"  [OK] {removed} source files removed (compiled only)")

        # Move .pyc files to same location (Python 3 puts them in __pycache__)
        pycache = os.path.join(build_plugin_dir, "__pycache__")
        if os.path.exists(pycache):
            for fname in os.listdir(pycache):
                if fname.endswith(".pyc"):
                    # Rename from module.cpython-312.pyc to module.pyc
                    base = fname.split(".")[0]
                    src = os.path.join(pycache, fname)
                    dst = os.path.join(build_plugin_dir, base + ".pyc")
                    shutil.move(src, dst)
            shutil.rmtree(pycache)
            print("  [OK] .pyc files relocated")

        # Package as ZIP
        output_path = os.path.abspath(f"{output_name}.zip")
        with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zf:
            for root, dirs, files in os.walk(build_plugin_dir):
                for f in files:
                    full_path = os.path.join(root, f)
                    arcname = os.path.relpath(full_path, build_dir)
                    zf.write(full_path, arcname)

        print("")
        print("=" * 60)
        print(f"RELEASE READY: {output_path}")
        print("=" * 60)
        print(f"Expiry:        {expiry_date or 'PERMANENT (no expiry)'}")
        print(f"Files:         .pyc only (no readable source)")
        print(f"Date hidden:   Obfuscated in license_checker.pyc")
        print("")
        print("This ZIP can be installed in QGIS directly.")
        print("Users cannot read or edit the expiration date.")
        return True

    finally:
        # Cleanup
        shutil.rmtree(build_dir, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(
        description="Build a protected FTTH Labeler release ZIP",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python build_release.py --expiry 2026-12-31
  python build_release.py --expiry 2026-06-30 --name ftth_user_a
  python build_release.py --permanent --name ftth_permanent
  python build_release.py --expiry 2026-01-15 --name ftth_15day_trial
        """
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--expiry", metavar="DATE",
                       help="Expiration date in YYYY-MM-DD format")
    group.add_argument("--permanent", action="store_true",
                       help="No expiration (permanent license)")
    parser.add_argument("--name", default="ftth_labeler_release",
                        help="Output ZIP name (without .zip)")
    parser.add_argument("--plugin-dir", default=None,
                        help="Path to ftth_labeler_v2 folder (auto-detected if omitted)")

    args = parser.parse_args()

    # Determine plugin directory
    if args.plugin_dir:
        plugin_dir = args.plugin_dir
    else:
        # Default: same directory as this script
        plugin_dir = os.path.dirname(os.path.abspath(__file__))

    if not os.path.exists(os.path.join(plugin_dir, "__init__.py")):
        # Try parent (script may be inside plugin folder)
        pass

    expiry = "" if args.permanent else args.expiry

    success = build_release(expiry, args.name, plugin_dir)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
